DATASET:
  NAME: 'cityscapes'
  NUM_CLASSES: 19
  DATAROOT: "D:/SACR/datasets/CityScapes"
  SCALE: [2048, 448]
  RATIO_RANGE: [0.5, 2.0]
  CROP_SIZE: [512, 512]
  CAT_MAX_RATIO: 0.75
  IMG_NORM_CFG:
    MEAN: [ 122.771, 116.746, 104.094 ]
    STD: [ 68.501, 66.632, 70.323 ]
    RGB: True
  TEXT_WEIGHT: 'text/city_ViT16_clip_text.pth'
  K: 2
  THRESHOLD: 21.5
  REDUCE_ZERO_LABEL: False
  IGNORE_INDEX: 255

MODEL:
  FEATURE_EXTRACTOR: 'vit'
  TEXT_CHANNEL: 512
  VISUAL_CHANNEL: 768
  TRAINING: True

TRAIN:
  BATCH_SIZE: 128
  MAX_EPOCH: 50
  EPOCH: 50
  LR: 0.16

TEST:
  BATCH_SIZE: 1

EVAL_METRIC: "miou"
SAVE_DIR: "experiments/city_rectification_modify_PAGG/"
NUM_WORKERS: 4
